// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package authdb

import (
	"time"
)

type Admin struct {
	UserID string `json:"user_id"`
}

type Auth struct {
	UserID         string    `json:"user_id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type RevokedToken struct {
	Token  string `json:"token"`
	UserID string `json:"user_id"`
}
