version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - task-service
      - rpg-service
      - feat-service
      - update-service
      - auth-service
    networks:
      - rabbitmq_go_net

  task-service:
    build:
      context: .
      dockerfile: cmd/task-service/Dockerfile
    environment:
      - TASK_DB_URL
      - TASK_DB_TOKEN
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  rpg-service:
    build:
      context: .
      dockerfile: cmd/rpg-service/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
      - RPG_DB_URL
      - RPG_DB_TOKEN
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_go_net

  feat-service:
    build:
      context: .
      dockerfile: cmd/feat-service/Dockerfile
    environment:
      - ACH_DB_URL
      - ACH_DB_TOKEN
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  update-service:
    build:
      context: .
      dockerfile: cmd/update-service/Dockerfile
    environment:
      - UPDATE_DB_URL
      - UPDATE_DB_TOKEN
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  auth-service:
    build:
      context: .
      dockerfile: cmd/auth-service/Dockerfile
    environment:
      - AUTH_DB_URL
      - AUTH_DB_TOKEN
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: cmd/user-service/Dockerfile
    environment:
      - USER_DB_URL
      - USER_DB_TOKEN
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 10s
        timeout: 10s
        retries: 5

networks:
  rabbitmq_go_net:
    driver: bridge
