version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.hbit.dev`)"
      - "traefik.http.routers.api.entrypoints=web"

  tasks-service:
    build:
      context: ./cmd/tasks-service
      Dockerfile: Dockerfile
    environment:
      - TASK_DB_URL
      - TASK_DB_TOKEN
      - RABBITMQ_URL:
          amqp://guest:guest@message-broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tasks-service.rule=Host(`api.hbit.dev`) && PathPrefix(`/tasks`)"
      - "traefik.http.services.tasks-service.loadbalancer.server.port=80" 
      - "traefik.http.middlewares.strip-tasks-prefix.stripprefix.prefixes=/tasks"
      - "traefik.http.routers.tasks-service.middlewares=strip-tasks-prefix"
      - "traefik.http.routers.tasks-service.middlewares=auth-check"
    container-name: 'hbit-tasks'

  rpg-service:
    build:
      context: ./cmd/rpg-service
      Dockerfile: Dockerfile
    environment:
      RABBITMQ_URL:
        amqp://guest:guest@message-broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpg-service.rule=Host(`api.hbit.dev`) && PathPrefix(`/rpg`)"
      - "traefik.http.services.rpg-service.loadbalancer.server.port=80"
      - "traefik.http.middlewares.strip-rpg-prefix.stripprefix.prefixes=/rpg"
      - "traefik.http.routers.rpg-service.middlewares=strip-rpg-prefix"
      - "traefik.http.routers.tasks-service.middlewares=auth-check"
    container-name: 'hbit-rpg'

  feats-service:
    build:
      context: ./cmd/feats
      Dockerfile: Dockerfile
    environment:
      - ACH_DB_URL
      - ACH_DB_TOKEN
      - RABBITMQ_URL:
          amqp://guest:guest@message-broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feats-service.rule=Host(`api.hbit.dev`) && PathPrefix(`/feats`)"
      - "traefik.http.services.feats-service.loadbalancer.server.port=80" 
      - "traefik.http.middlewares.strip-feats-prefix.stripprefix.prefixes=/feats"
      - "traefik.http.routers.feats-service.middlewares=strip-feats-prefix"
      - "traefik.http.routers.tasks-service.middlewares=auth-check"
    container-name: 'hbit-feats'

  updates-service:
    build:
      context: ./cmd/updates-service
      Dockerfile: Dockerfile
    environment:
      - UPDATE_DB_URL
      - UPDATE_DB_TOKEN
      - RABBITMQ_URL:
          amqp://guest:guest@message-broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feats-service.rule=Host(`api.hbit.dev`) && PathPrefix(`/updates`)"
      - "traefik.http.services.feats-service.loadbalancer.server.port=80" 
      - "traefik.http.middlewares.strip-updates-prefix.stripprefix.prefixes=/updates"
      - "traefik.http.routers.updates-service.middlewares=strip-updates-prefix"
      - "traefik.http.routers.tasks-service.middlewares=auth-check"
    container-name: 'hbit-updates'

  auth-service:
    build:
      context: ./cmd/auth-service
      Dockerfile: Dockerfile
    environment:
      - AUTH_DB_URL
      - AUTH_DB_TOKEN
      - RABBITMQ_URL:
          amqp://guest:guest@message-broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=Host(`api.hbit.dev`) && PathPrefix(`/auth`)"
      - "traefik.http.services.auth-service.loadbalancer.server.port=80" 
      - "traefik.http.middlewares.strip-updates-prefix.stripprefix.prefixes=/auth"
      - "traefik.http.routers.auth-service.middlewares=strip-updates-prefix"
      - "traefik.http.middlewares.auth-verify.forwardauth.address=http://auth-service:80/auth/verify"
      - "traefik.http.middlewares.auth-verify.forwardauth.authResponseHeaders=X-User-ID"
    container_name: 'hbit-auth'

  message-broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  volumes:
    rabbitmq_data:
