// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package userdb

import (
	"time"
)

type UserSetting struct {
	UserID             string    `json:"user_id"`
	Theme              string    `json:"theme"`
	DisplayName        string    `json:"display_name"`
	Email              string    `json:"email"`
	EmailNotifications bool      `json:"email_notifications"`
	ResetTime          string    `json:"reset_time"`
	UserTimezone       string    `json:"user_timezone"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}
