// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package taskdb

import (
	"time"
)

type Task struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Title       string    `json:"title"`
	Text        string    `json:"text"`
	IsCompleted bool      `json:"is_completed"`
	TaskType    string    `json:"task_type"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Difficulty  string    `json:"difficulty"`
}
