// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: auth.sql

package rpgdb

import (
	"context"
)

const deleteUserData = `-- name: DeleteUserData :exec
DELETE FROM
    user_quest
WHERE
    user_id = ?
`

func (q *Queries) DeleteUserData(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserData, userID)
	return err
}
