// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package rpgdb

import (
	"time"
)

type CharacterBackup struct {
	UserID         string `json:"user_id"`
	ClassID        string `json:"class_id"`
	CharacterLevel int64  `json:"character_level"`
	Experience     int64  `json:"experience"`
	Health         int64  `json:"health"`
	Mana           int64  `json:"mana"`
	Strength       int64  `json:"strength"`
	Dexterity      int64  `json:"dexterity"`
	Intelligence   int64  `json:"intelligence"`
}

type CharacterClass struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CharacterState struct {
	EventID        string    `json:"event_id"`
	UserID         string    `json:"user_id"`
	ClassID        string    `json:"class_id"`
	CharacterLevel int64     `json:"character_level"`
	Experience     int64     `json:"experience"`
	Health         int64     `json:"health"`
	Mana           int64     `json:"mana"`
	Strength       int64     `json:"strength"`
	Dexterity      int64     `json:"dexterity"`
	Intelligence   int64     `json:"intelligence"`
	Timestamp      time.Time `json:"timestamp"`
}

type Item struct {
	ItemID      string    `json:"item_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Href        string    `json:"href"`
	StrBoost    int64     `json:"str_boost"`
	DexBoost    int64     `json:"dex_boost"`
	IntBoost    int64     `json:"int_boost"`
	Slot        string    `json:"slot"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ItemBackup struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	ItemType    string  `json:"item_type"`
	Attributes  *string `json:"attributes"`
}

type Quest struct {
	QuestID     string    `json:"quest_id"`
	QuestType   string    `json:"quest_type"`
	Description string    `json:"description"`
	Title       string    `json:"title"`
	Details     string    `json:"details"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type QuestBackup struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	Description  string  `json:"description"`
	Requirements *string `json:"requirements"`
	Rewards      *string `json:"rewards"`
}

type QuestItem struct {
	QuestID          string `json:"quest_id"`
	ItemID           string `json:"item_id"`
	QuantityRequired int64  `json:"quantity_required"`
}

type UserQuest struct {
	UserID    string    `json:"user_id"`
	QuestID   string    `json:"quest_id"`
	Completed bool      `json:"completed"`
	Timestamp time.Time `json:"timestamp"`
	EventID   string    `json:"event_id"`
	Details   string    `json:"details"`
}

type UserQuestBackup struct {
	UserID    string `json:"user_id"`
	QuestID   string `json:"quest_id"`
	Completed bool   `json:"completed"`
}
