// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: quest.sql

package rpgdb

import (
	"context"
)

const listQuests = `-- name: ListQuests :many
SELECT
    quest_id, quest_type, description, title, details, created_at, updated_at
FROM
    quest
`

func (q *Queries) ListQuests(ctx context.Context) ([]Quest, error) {
	rows, err := q.db.QueryContext(ctx, listQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.QuestID,
			&i.QuestType,
			&i.Description,
			&i.Title,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
