// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_data.sql

package rpgdb

import (
	"context"
)

const deleteUserCharacterData = `-- name: DeleteUserCharacterData :exec
DELETE FROM
    character_state
WHERE
    user_id = ?
`

func (q *Queries) DeleteUserCharacterData(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserCharacterData, userID)
	return err
}

const deleteUserQuestData = `-- name: DeleteUserQuestData :exec
DELETE FROM
    user_quest
WHERE
    user_id = ?
`

func (q *Queries) DeleteUserQuestData(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserQuestData, userID)
	return err
}
