// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Quest struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	Description  string  `json:"description"`
	Requirements *string `json:"requirements"`
	Rewards      *string `json:"rewards"`
}

type QuestItem struct {
	QuestID          string `json:"quest_id"`
	ItemID           string `json:"item_id"`
	QuantityRequired int64  `json:"quantity_required"`
}

type UserQuest struct {
	UserID    int64 `json:"user_id"`
	QuestID   int64 `json:"quest_id"`
	Completed bool  `json:"completed"`
}
