// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Character struct {
	UserID         string `json:"user_id"`
	ClassID        string `json:"class_id"`
	CharacterLevel int64  `json:"character_level"`
	Experience     int64  `json:"experience"`
	Health         int64  `json:"health"`
	Mana           int64  `json:"mana"`
	Strength       int64  `json:"strength"`
	Dexterity      int64  `json:"dexterity"`
	Intelligence   int64  `json:"intelligence"`
}

type CharacterClass struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Item struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	ItemType    string  `json:"item_type"`
	Attributes  *string `json:"attributes"`
}
