// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_data.sql

package featdb

import (
	"context"
)

const deleteUserFeats = `-- name: DeleteUserFeats :exec
DELETE FROM
    user_feats
WHERE
    user_id = ?
`

func (q *Queries) DeleteUserFeats(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserFeats, userID)
	return err
}

const deleteUserQuestLogs = `-- name: DeleteUserQuestLogs :exec
DELETE FROM
    quest_log
WHERE
    user_id = ?
`

func (q *Queries) DeleteUserQuestLogs(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserQuestLogs, userID)
	return err
}

const deleteUserTaskLogs = `-- name: DeleteUserTaskLogs :exec
DELETE FROM
    task_log
WHERE
    user_id = ?
`

func (q *Queries) DeleteUserTaskLogs(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserTaskLogs, userID)
	return err
}
