// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: admin.sql

package database

import (
	"context"
)

const isAdmin = `-- name: IsAdmin :one
SELECT
    user_id
FROM
    admin
WHERE
    user_id = ?
`

func (q *Queries) IsAdmin(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, isAdmin, userID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
